### ISSUE TITLE
blast samples needed.

### ISSUE THREAD

**Issue by flycatcher27** [noahs-bark/kaboom#1]
To get the activity going, we need to collect audio blast samples. 

Can we also create a folder in github to store them? Or should we have a project specific shared drive?

**Comment by scamanderandco** [comment]
We should be using a shared drive -  Google drive or Dropbox because the size will run into MBs at least is not GBs

**Comment by flycatcher27** [comment]
Does anyone have connections with a library of sounds? (on the lines of Library of Natural Sounds - Cornell)

**Comment by flycatcher27** [comment]
Thanks to Abhi I have the samples and prior work as well. 

They are here: https://github.com/noahs-bark/kaboom/tree/master/Dynamite%20Blast%20Detection_Jan2017

I'm closing this issue.
