### ISSUE TITLE
Problem Statement

### ISSUE THREAD

**Issue by sharathm** [noahs-bark/kaboom#2]
Prepare a problem statement that can be shared via PPT or other formats. This can be used to pitch for funds / help at corporate locations.

**Comment by noahbites** [comment]
Happy New Year folks!

Hopefully I'll be cruising through Github in the coming months!

**Comment by noahbites** [comment]
Problem Statement

Title - Acoustic detection systems for monitoring gunshots and dynamite blasts

Objective - To accurately detect and identify locations of gunshots and dynamite blasts in ecologically important areas

Background - 

1. Protected areas (PAs) occupy less than 4% of landmass in India but are plagued with challenges 
2. Faced by shortage of staff, infrastructure and equipment most PAs are unable to protect and conserve biodiversity
3. One serious threat to wildlife both within and outside the PAs are hunting and poaching using guns and other firearms
4. In many forests, it is a challenge to hear and locate gunshots owing to terrain, remoteness etc. Responding to incidents of gunfire in as quickly as possible will greatly help enforce laws to protect wildlife.  
5. The other threat on similar lines is the use of explosives to kill fish and other aquatic fauna
6. Most rivers have experienced or continue to experience dynamite fishing (or blast fishing) as a quick and easy way to kill fish and make money. But this method kills and maims indiscriminately, everything in the blast radius. Highly destructive to the environment, it also robs the livelihood of traditional fishermen for years to come.
7. ..........

Methods-
Using a smartphone as a starting point ???

1. A modular system to detect both gunshots and dynamite blasts 
2. Ability to transmit data in real-time
3. Solar powered to withstand long periods of field deployment
4. Weather-proof to withstand the elements
5. Ability to work in areas without network coverage

**Comment by pvineet** [comment]
https://github.com/noahs-bark/kaboom/wiki/Problem-Statement

**Comment by scamanderandco** [comment]
Shall I close this issue for now?

**Comment by noahbites** [comment]
There's a minor update to the draft. Also, how did you convert that into a Wiki?

**Comment by pvineet** [comment]
I added it to the wiki :-)
You can edit the wiki @
https://github.com/noahs-bark/kaboom/wiki/Problem-Statement

**Comment by noahbites** [comment]
Sorry, how  do I edit the wiki? I don't see an option

**Comment by pvineet** [comment]
There are two buttons edit and new page on this page
https://github.com/noahs-bark/kaboom/wiki/Problem-Statement
Use the edit button

**Comment by pvineet** [comment]
https://help.github.com/articles/editing-wiki-pages-via-the-online-interface/

**Comment by noahbites** [comment]
Oh! I don't have any repositories. 

Is kaboom a repository?? unable to find and add

**Comment by flycatcher27** [comment]
Agree. I'm closing the issue.

**Comment by flycatcher27** [comment]
No worries. Here is the link to the wiki:

https://github.com/noahs-bark/kaboom/wiki/Problem-Statement
